declare const enum SortFilters {
    CLOSING_SOON = "CLOSING_SOON",
    ALPHABETICAL_ASC = "ALPHABETICAL_ASC",
    ALPHABETICAL_DESC = "ALPHABETICAL_DESC",
    BIDS_ASC = "BIDS_ASC", 
    BIDS_DESC = "BIDS_DESC", 
    CLOSING_LAST = "CLOSING_LAST", 
    RESERVE_ASC = "RESERVE_ASC", 
    RESERVE_DESC = "RESERVE_DESC"
  }